/* ============================================================
   QUIZ QUESTION BANK
   ------------------------------------------------------------
   Structure:
     QUESTIONS[sportId] = [ {question}, ... ]

   Each question:
     id              unique short string
     type            "mc" | "tf" | "image"
     panel           (optional) which rules panel this maps to
     img             (only for type:"image") path to existing image
     prompt          the question text shown to the kid
     answer          the correct answer
                       - "mc" / "image" : string that must also appear among options
                       - "tf"           : true | false
     easyDistractors (mc/image only) 2 obviously wrong choices, shown on Easy
     hardDistractors (mc/image only) 3 plausible/tricky wrong choices, shown on Hard
     hint            short hint shown on Easy when the kid clicks 💡

   Authoring guidelines:
   - ~50 questions per sport, spread across the rules panels.
   - Easy distractors: clearly wrong, often silly.
   - Hard distractors: plausible — close-but-not-quite rules.
   - Questions answerable from the image rules cards in /images.
   ============================================================ */

const QUESTIONS = {
  /* ============================================================
     FLAG FOOTBALL — 50 questions across 5 panels
     ============================================================ */
  flag: [
    /* ---------- Panel 1: Field & Game Flow ---------- */
    {id:"ff-01", type:"mc", panel:1,
      prompt:"How does a defender stop the ball carrier in flag football?",
      answer:"Pull one of their flags",
      easyDistractors:["Tackle them to the ground","Sit on them"],
      hardDistractors:["Tag them with two hands","Wrap them up gently","Block their path until they stop"],
      hint:"The sport is named after this action."},
    {id:"ff-02", type:"tf", panel:1,
      prompt:"Tackling is allowed in flag football.", answer:false,
      hint:"It's called FLAG football, not tackle football."},
    {id:"ff-03", type:"mc", panel:1,
      prompt:"How many players are usually on the field per team in youth flag football (5v5)?",
      answer:"5",
      easyDistractors:["11","20"],
      hardDistractors:["7","6","4"],
      hint:"The format is called 5-on-5."},
    {id:"ff-04", type:"mc", panel:1,
      prompt:"What's the goal of the offense on each drive?",
      answer:"Move the ball toward the end zone to score",
      easyDistractors:["Run out the clock the whole game","Throw the ball out of bounds"],
      hardDistractors:["Make four punts in a row","Force the defense to substitute","Hand the ball to the referee"],
      hint:"You want to reach the end zone."},
    {id:"ff-05", type:"mc", panel:1,
      prompt:"How many points is a touchdown worth?",
      answer:"6",
      easyDistractors:["1","100"],
      hardDistractors:["3","7","2"],
      hint:"Same as tackle football."},
    {id:"ff-06", type:"tf", panel:1,
      prompt:"A game is divided into two halves.", answer:true,
      hint:"Like soccer or basketball."},
    {id:"ff-07", type:"mc", panel:1,
      prompt:"What does the offense get when they reach the end zone with the ball?",
      answer:"A touchdown",
      easyDistractors:["A penalty","A timeout"],
      hardDistractors:["A first down","A safety","A field goal"],
      hint:"Six points!"},
    {id:"ff-08", type:"tf", panel:1,
      prompt:"The team without the ball is called the defense.", answer:true,
      hint:"Offense has the ball, defense tries to stop them."},
    {id:"ff-09", type:"image", panel:1, img:"images/Flag_Football_1.png",
      prompt:"Which panel shows the field layout and game flow?",
      answer:"Field & Game Flow",
      easyDistractors:["Basic Drills","Technique Tips"],
      hardDistractors:["Player Roles","Basic Tactics","Pre-game Warmup"],
      hint:"Look at the panel title."},

    /* ---------- Panel 2: Player Roles, Stance & Rules ---------- */
    {id:"ff-10", type:"mc", panel:2,
      prompt:"Who throws the ball on offense?",
      answer:"The quarterback",
      easyDistractors:["The referee","The coach"],
      hardDistractors:["The center","The wide receiver","The rusher"],
      hint:"QB for short."},
    {id:"ff-11", type:"mc", panel:2,
      prompt:"Who snaps the ball to start a play?",
      answer:"The center",
      easyDistractors:["The mascot","A parent"],
      hardDistractors:["The quarterback","The receiver","The safety"],
      hint:"They are in the center of the line."},
    {id:"ff-12", type:"mc", panel:2,
      prompt:"What does a wide receiver mainly do?",
      answer:"Run routes and catch passes",
      easyDistractors:["Watch from the sideline","Hold the cones"],
      hardDistractors:["Snap the ball","Call the plays","Pull flags on defense"],
      hint:"They catch the ball."},
    {id:"ff-13", type:"tf", panel:2,
      prompt:"Players must wear their flags on the outside of their clothing so they are easy to grab.",
      answer:true,
      hint:"If flags are hidden it isn't fair."},
    {id:"ff-14", type:"mc", panel:2,
      prompt:"What is 'flag guarding'?",
      answer:"Using your hands or arms to block a defender from your flags",
      easyDistractors:["Wearing extra flags","Eating a snack mid-play"],
      hardDistractors:["Tying your flags tightly","Switching flags with a teammate","Wearing your flag belt backwards"],
      hint:"It's something the ball carrier is NOT allowed to do."},
    {id:"ff-15", type:"tf", panel:2,
      prompt:"Flag guarding is allowed.", answer:false,
      hint:"It would make defenders' job impossible."},
    {id:"ff-16", type:"mc", panel:2,
      prompt:"Which stance is the quarterback usually in before the snap?",
      answer:"Standing a step behind the center, ready to receive the snap",
      easyDistractors:["Lying on their back","Sitting on the ground"],
      hardDistractors:["Sprinting backwards","Down in a three-point stance like a lineman","Facing the sideline"],
      hint:"They need to see the field and catch the snap."},
    {id:"ff-17", type:"tf", panel:2,
      prompt:"Defenders are allowed to dive at the ball carrier's legs.", answer:false,
      hint:"That's a tackling motion — not allowed in flag football."},
    {id:"ff-18", type:"mc", panel:2,
      prompt:"What happens if a defender pulls a player's flag before they catch the ball?",
      answer:"It's a penalty (flag pulling before possession)",
      easyDistractors:["The defender gets extra points","The receiver is out of the game"],
      hardDistractors:["The play continues normally","The offense loses the ball","The clock stops automatically"],
      hint:"You can only pull the flag of the ball carrier."},

    /* ---------- Panel 3: Basic Drills ---------- */
    {id:"ff-19", type:"mc", panel:3,
      prompt:"Why do players warm up before a drill or game?",
      answer:"To get muscles ready and prevent injury",
      easyDistractors:["To use up game time","Because the coach is bored"],
      hardDistractors:["To tire teammates out","To make the field longer","To skip practice early"],
      hint:"Cold muscles get hurt more easily."},
    {id:"ff-20", type:"tf", panel:3,
      prompt:"Catching drills help you practice keeping your eyes on the ball.", answer:true,
      hint:"Watch the ball all the way into your hands."},
    {id:"ff-21", type:"mc", panel:3,
      prompt:"What's a key part of a good throwing motion?",
      answer:"Step toward your target with the opposite foot",
      easyDistractors:["Close your eyes when you release","Throw with your back to the target"],
      hardDistractors:["Step with the same foot as your throwing arm","Spin in a circle first","Jump high and throw at the peak"],
      hint:"Right-handed throwers step with the left foot."},
    {id:"ff-22", type:"mc", panel:3,
      prompt:"How should your hands look when catching the ball above your chest?",
      answer:"Thumbs together making a diamond shape",
      easyDistractors:["Hands in your pockets","One hand only, behind your back"],
      hardDistractors:["Pinkies together","Fists closed tight","Hands crossed"],
      hint:"Pinkies down, thumbs in — diamond!"},
    {id:"ff-23", type:"tf", panel:3,
      prompt:"Drills should usually start slow and get faster as you get more comfortable.", answer:true,
      hint:"Form first, speed second."},
    {id:"ff-24", type:"mc", panel:3,
      prompt:"Which drill helps you practice pulling flags?",
      answer:"A 1-on-1 chase-and-pull drill",
      easyDistractors:["A quiet reading drill","A snack-break drill"],
      hardDistractors:["A backpedal-only drill","A long-jump drill","A blocking drill"],
      hint:"You actually grab a flag in the drill."},
    {id:"ff-25", type:"image", panel:3, img:"images/Flag_Football_3.png",
      prompt:"Which panel shows the basic drills you practice?",
      answer:"Basic Drills",
      easyDistractors:["Field & Game Flow","Technique Tips"],
      hardDistractors:["Basic Tactics","Player Roles","Stretch Routine"],
      hint:"Read the title at the top of the panel."},

    /* ---------- Panel 4: Basic Tactics ---------- */
    {id:"ff-26", type:"mc", panel:4,
      prompt:"What is a 'route'?",
      answer:"The path a receiver runs to get open for a pass",
      easyDistractors:["A type of snack","A song the team sings"],
      hardDistractors:["The line the defense forms","The way to the parking lot","A timeout signal"],
      hint:"Like a map for the receiver."},
    {id:"ff-27", type:"mc", panel:4,
      prompt:"A 'slant' route means the receiver…",
      answer:"…runs at an angle across the field",
      easyDistractors:["…stops and waves","…runs to the snack table"],
      hardDistractors:["…runs straight ahead 40 yards","…spins three times then jumps","…runs backwards"],
      hint:"It's a slanted line, not straight."},
    {id:"ff-28", type:"tf", panel:4,
      prompt:"A 'go' route means the receiver runs straight downfield as fast as they can.",
      answer:true,
      hint:"Just go!"},
    {id:"ff-29", type:"mc", panel:4,
      prompt:"Why do teams use different plays?",
      answer:"To trick the defense and find open receivers",
      easyDistractors:["To confuse their own team","To make the game last longer"],
      hardDistractors:["Because the rules require a new play each down","To tire out the referee","To use up timeouts"],
      hint:"Mixing it up keeps the defense guessing."},
    {id:"ff-30", type:"mc", panel:4,
      prompt:"What does 'man-to-man' defense mean?",
      answer:"Each defender covers one specific offensive player",
      easyDistractors:["All defenders stand still","Defenders watch from the bench"],
      hardDistractors:["Defenders cover zones of the field","Only one defender plays at a time","Defenders rotate every second"],
      hint:"One-on-one matchups."},
    {id:"ff-31", type:"mc", panel:4,
      prompt:"What does 'zone' defense mean?",
      answer:"Each defender guards an area of the field",
      easyDistractors:["Defenders form a single-file line","Defenders stay in the end zone"],
      hardDistractors:["Each defender follows one offensive player","Defenders only chase the quarterback","Defenders rotate every play"],
      hint:"Think of an area, not a person."},
    {id:"ff-32", type:"tf", panel:4,
      prompt:"A 'rusher' is a defender who runs toward the quarterback to disrupt the throw.",
      answer:true,
      hint:"They rush the QB."},
    {id:"ff-33", type:"mc", panel:4,
      prompt:"In most youth leagues, how far back must the rusher start from the line of scrimmage?",
      answer:"About 7 yards back",
      easyDistractors:["Right next to the center","100 yards away"],
      hardDistractors:["3 yards back","10 yards back","On the sideline"],
      hint:"Far enough that the QB has time to throw."},

    /* ---------- Panel 5: Technique Tips ---------- */
    {id:"ff-34", type:"mc", panel:5,
      prompt:"Where should you look when running with the ball?",
      answer:"Forward, to see defenders and where to go",
      easyDistractors:["At your shoes","At the sky"],
      hardDistractors:["Only at the ball","Behind you constantly","At the scoreboard"],
      hint:"You need to see what's coming."},
    {id:"ff-35", type:"mc", panel:5,
      prompt:"How should you carry the ball?",
      answer:"Tucked tight against your body with both hands or one strong grip",
      easyDistractors:["Balanced on your head","Inside your shirt"],
      hardDistractors:["Held high above your head","Bouncing on the ground","Loosely under one arm"],
      hint:"Don't drop it!"},
    {id:"ff-36", type:"tf", panel:5,
      prompt:"Faking with your eyes or hips can help you get past a defender.", answer:true,
      hint:"Make them think you're going one way, then go the other."},
    {id:"ff-37", type:"mc", panel:5,
      prompt:"When catching the ball, you should…",
      answer:"…watch the ball all the way into your hands",
      easyDistractors:["…close your eyes","…look at the defender instead"],
      hardDistractors:["…catch with your eyes shut","…wait for it to bounce first","…look at the sideline"],
      hint:"Eyes on the ball!"},
    {id:"ff-38", type:"mc", panel:5,
      prompt:"Best way to pull a flag?",
      answer:"Grab the flag itself with a firm grip and pull straight down or away",
      easyDistractors:["Grab the player's shirt","Stomp on the flag"],
      hardDistractors:["Slap at the flag without grabbing","Pull the player's arm","Tug on the belt buckle"],
      hint:"Grab the cloth flag, not the player."},
    {id:"ff-39", type:"tf", panel:5,
      prompt:"Pushing or holding a player to pull their flag is OK.", answer:false,
      hint:"Pull the flag — not the person."},
    {id:"ff-40", type:"mc", panel:5,
      prompt:"When throwing the ball, where should your fingers be on the laces?",
      answer:"Lightly on the laces for control and spin",
      easyDistractors:["Inside the ball","Not touching the ball at all"],
      hardDistractors:["Squeezing as hard as possible","Only on the tip of the ball","On the back tip away from the laces"],
      hint:"Laces help you spin the ball."},
    {id:"ff-41", type:"mc", panel:5,
      prompt:"Best body position for a defender?",
      answer:"Knees bent, low stance, ready to move in any direction",
      easyDistractors:["Standing perfectly straight, arms folded","Sitting cross-legged"],
      hardDistractors:["Lying flat","Walking backwards casually","Hands in pockets"],
      hint:"Athletic stance — like a basketball player on defense."},

    /* ---------- Mixed / general ---------- */
    {id:"ff-42", type:"tf", panel:1,
      prompt:"You can stiff-arm a defender to keep them away.", answer:false,
      hint:"No contact like that in flag football."},
    {id:"ff-43", type:"mc", panel:2,
      prompt:"What signals the start of each play?",
      answer:"The snap from the center to the quarterback",
      easyDistractors:["A whistle from a player","The crowd cheering"],
      hardDistractors:["A coin toss","The referee blowing a horn","The receiver raising a hand"],
      hint:"It comes from the center."},
    {id:"ff-44", type:"tf", panel:1,
      prompt:"Once your flag is pulled, the play is over for you.", answer:true,
      hint:"That's the whole point of pulling flags."},
    {id:"ff-45", type:"mc", panel:4,
      prompt:"What does the offense usually do in the huddle?",
      answer:"Pick the next play",
      easyDistractors:["Take a nap","Order pizza"],
      hardDistractors:["Vote for a new captain","Stretch","Drink water silently"],
      hint:"Quick team meeting before the play."},
    {id:"ff-46", type:"tf", panel:2,
      prompt:"Only the quarterback is allowed to throw a forward pass on a play (in most youth rules).",
      answer:true,
      hint:"Usually, yes — special trick plays aside."},
    {id:"ff-47", type:"mc", panel:5,
      prompt:"A good way to celebrate after a touchdown?",
      answer:"High-five your team and respect the other team",
      easyDistractors:["Mock the other team","Throw the ball into the stands"],
      hardDistractors:["Run another lap","Refuse to give the ball back","Brag for five minutes"],
      hint:"Be a good sport!"},
    {id:"ff-48", type:"mc", panel:1,
      prompt:"What is a 'first down'?",
      answer:"When the offense advances the ball far enough to get a new set of downs",
      easyDistractors:["The first time anyone falls down","The first play of the game"],
      hardDistractors:["A penalty against the defense","A type of timeout","A score worth 1 point"],
      hint:"It resets your downs."},
    {id:"ff-49", type:"tf", panel:3,
      prompt:"Cool-down stretching after a game helps your muscles recover.", answer:true,
      hint:"Warm up before, cool down after."},
    {id:"ff-50", type:"mc", panel:4,
      prompt:"Why is communication important on defense?",
      answer:"So teammates know who is covering whom and avoid mistakes",
      easyDistractors:["So everyone can sing together","To distract teammates"],
      hardDistractors:["To impress the coach","To use up time on the clock","Because the rules require it"],
      hint:"Defenders talk so no one is left uncovered."}
  ],

  /* ============================================================
     SWIMMING — 50 questions across 8 panels
     ============================================================ */
  swim: [
    /* ---------- Panel 1: My Swim Meet Day ---------- */
    {id:"sw-01", type:"mc", panel:1,
      prompt:"What should you bring to a swim meet?",
      answer:"Swimsuit, cap, goggles, towel, and water",
      easyDistractors:["Only a soccer ball","Roller skates and a kite"],
      hardDistractors:["A wetsuit and snorkel","Flippers and a snorkel","A backpack of toys"],
      hint:"Think of everything you need in and out of the water."},
    {id:"sw-02", type:"tf", panel:1,
      prompt:"It's important to arrive early for warm-up at a swim meet.", answer:true,
      hint:"You need time to stretch and warm up in the pool."},
    {id:"sw-03", type:"mc", panel:1,
      prompt:"What is the 'heat sheet' at a meet?",
      answer:"A list showing which swimmers race in which heat and lane",
      easyDistractors:["A piece of paper that's warm","A snack menu"],
      hardDistractors:["The rulebook","A medal list","A pool cleaning schedule"],
      hint:"It tells you when and where you swim."},
    {id:"sw-04", type:"tf", panel:1,
      prompt:"You should eat a huge meal right before your race.", answer:false,
      hint:"A big meal too close to a race can upset your stomach."},
    {id:"sw-05", type:"mc", panel:1,
      prompt:"What does the 'check-in' (or 'clerk of course') desk do?",
      answer:"Confirms swimmers are present and ready for their race",
      easyDistractors:["Hands out medals before the race","Gives out free pizza"],
      hardDistractors:["Sets the world records","Cleans the lane lines","Picks the music"],
      hint:"They check you in for your event."},
    {id:"sw-06", type:"image", panel:1, img:"images/Swimming_1.png",
      prompt:"Which panel walks you through your swim meet day?",
      answer:"My Swim Meet Day",
      easyDistractors:["Disqualification Rules","Relay Rules"],
      hardDistractors:["Start Rules","Sportsmanship & Etiquette","General Race Rules"],
      hint:"Look at the panel title."},

    /* ---------- Panel 2: Start Rules ---------- */
    {id:"sw-07", type:"mc", panel:2,
      prompt:"What signal starts a swim race?",
      answer:"A horn or beep (and a flash on the starter signal)",
      easyDistractors:["A whistle from a teammate","A song from the coach"],
      hardDistractors:["The referee says 'swim'","A bell only","The crowd clapping"],
      hint:"It's a loud sound from the starting system."},
    {id:"sw-08", type:"tf", panel:2,
      prompt:"Diving in before the start signal is allowed if you're sure you'll be fast.", answer:false,
      hint:"That's called a false start."},
    {id:"sw-09", type:"mc", panel:2,
      prompt:"What is a 'false start'?",
      answer:"Leaving the block before the start signal",
      easyDistractors:["Saying 'good luck' too loudly","Forgetting your goggles"],
      hardDistractors:["Finishing the race second","Touching the wrong wall","Wearing two caps"],
      hint:"Starting too early."},
    {id:"sw-10", type:"mc", panel:2,
      prompt:"What command means swimmers should get into starting position?",
      answer:"'Take your mark'",
      easyDistractors:["'Go to lunch'","'Have a seat'"],
      hardDistractors:["'Ready, set'","'On your mark, get set, go'","'Stand by'"],
      hint:"It's three short words."},
    {id:"sw-11", type:"tf", panel:2,
      prompt:"The backstroke starts in the water, not on the block.", answer:true,
      hint:"Backstrokers hold the wall and push off backwards."},
    {id:"sw-12", type:"mc", panel:2,
      prompt:"Where do backstroke swimmers grip before the start?",
      answer:"The starting grip / wall, with feet against the wall under the water",
      easyDistractors:["The lane rope","The flag pole on deck"],
      hardDistractors:["A bar above the pool","The starter's hand","Each other's caps"],
      hint:"Hands on the wall, feet on the wall."},
    {id:"sw-13", type:"tf", panel:2,
      prompt:"You should remain still and quiet after 'take your mark' until the start signal.", answer:true,
      hint:"Movement can cause a false start."},

    /* ---------- Panel 3: General Race Rules ---------- */
    {id:"sw-14", type:"mc", panel:3,
      prompt:"Which lane must you stay in during your race?",
      answer:"Your own lane",
      easyDistractors:["Any lane that looks empty","The lane with the prettiest color"],
      hardDistractors:["The middle lane only","The fastest lane","The lane next to your coach"],
      hint:"One swimmer per lane — stay in yours."},
    {id:"sw-15", type:"tf", panel:3,
      prompt:"You can hold the lane rope to pull yourself forward if you get tired.", answer:false,
      hint:"That would be using the equipment to gain advantage."},
    {id:"sw-16", type:"mc", panel:3,
      prompt:"How do you finish a race correctly?",
      answer:"Touch the wall as the rules of your stroke require",
      easyDistractors:["Yell 'done!' loudly","Throw your goggles in the air"],
      hardDistractors:["Step out of the pool","Touch the lane rope","Wait for the next swimmer"],
      hint:"Different strokes have different touch rules."},
    {id:"sw-17", type:"tf", panel:3,
      prompt:"Walking on the bottom of the pool to go faster is allowed.", answer:false,
      hint:"You must swim, not walk."},
    {id:"sw-18", type:"mc", panel:3,
      prompt:"When can you exit the pool after your race?",
      answer:"After you finish AND other swimmers in your heat have also finished (when allowed)",
      easyDistractors:["Whenever you feel like it during the race","Only on the next day"],
      hardDistractors:["Before the others start","Only when the coach blows a whistle","Only at the shallow end"],
      hint:"Be polite — wait so you don't make waves for others."},
    {id:"sw-19", type:"tf", panel:3,
      prompt:"Wearing a cap and goggles is common (and required in many meets).", answer:true,
      hint:"Caps keep hair tidy; goggles protect eyes."},
    {id:"sw-20", type:"mc", panel:3,
      prompt:"What should you do if your goggles fill with water mid-race?",
      answer:"Keep swimming and finish the race",
      easyDistractors:["Stop and call your coach","Climb out and try again later"],
      hardDistractors:["Switch to a teammate's goggles","Hold the lane rope while fixing them","Take them off and throw them"],
      hint:"Tough it out — you can fix them after."},

    /* ---------- Panel 4: Disqualification Rules ---------- */
    {id:"sw-21", type:"mc", panel:4,
      prompt:"What does DQ stand for?",
      answer:"Disqualified",
      easyDistractors:["Dive Quietly","Dry Quickly"],
      hardDistractors:["Deep Quarter","Double Qualifier","Dolphin Quest"],
      hint:"It means your race doesn't count due to a rule break."},
    {id:"sw-22", type:"tf", panel:4,
      prompt:"A false start can lead to a disqualification.", answer:true,
      hint:"Leaving early breaks the rules."},
    {id:"sw-23", type:"mc", panel:4,
      prompt:"In breaststroke, what's a common cause of disqualification?",
      answer:"An illegal kick (like a flutter kick instead of a frog kick)",
      easyDistractors:["Smiling at the judge","Wearing a red cap"],
      hardDistractors:["Breathing too often","Wearing two pairs of goggles","Splashing the next lane"],
      hint:"Breaststroke kick must be symmetrical."},
    {id:"sw-24", type:"mc", panel:4,
      prompt:"In butterfly, what's a common DQ?",
      answer:"Kicking with one leg instead of both legs together (no flutter kick)",
      easyDistractors:["Wearing the wrong color cap","Closing your eyes"],
      hardDistractors:["Breathing every two strokes","Touching the wall too gently","Wearing a snorkel"],
      hint:"Butterfly = dolphin kick, both legs together."},
    {id:"sw-25", type:"tf", panel:4,
      prompt:"Pulling on the lane rope can cause disqualification.", answer:true,
      hint:"You can't use the equipment to help you go faster."},
    {id:"sw-26", type:"mc", panel:4,
      prompt:"What can disqualify a backstroker at the finish?",
      answer:"Turning over onto the stomach before touching the wall",
      easyDistractors:["Smiling","Wearing two caps"],
      hardDistractors:["Touching with two hands","Breathing too much","Closing the eyes"],
      hint:"Backstrokers must stay on their back to the touch."},
    {id:"sw-27", type:"tf", panel:4,
      prompt:"Touching the wall with only one hand in breaststroke is allowed at the finish.", answer:false,
      hint:"Both hands must touch at the same time."},

    /* ---------- Panel 5: Freestyle & Backstroke ---------- */
    {id:"sw-28", type:"mc", panel:5,
      prompt:"In freestyle, you may swim any stroke EXCEPT in a medley — what's the most common choice?",
      answer:"Front crawl",
      easyDistractors:["Doggie paddle","Floating only"],
      hardDistractors:["Breaststroke","Sidestroke","Elementary backstroke"],
      hint:"The fastest stroke."},
    {id:"sw-29", type:"tf", panel:5,
      prompt:"In freestyle, you can touch the wall with any part of your body to finish.", answer:true,
      hint:"It's the most flexible stroke for finishes."},
    {id:"sw-30", type:"mc", panel:5,
      prompt:"In backstroke, what position must you stay in?",
      answer:"On your back",
      easyDistractors:["Standing up","Sitting on the lane rope"],
      hardDistractors:["On your side","On your stomach","Spinning"],
      hint:"It's in the name."},
    {id:"sw-31", type:"mc", panel:5,
      prompt:"What's the legal turn in backstroke (in most rules)?",
      answer:"You may turn onto your stomach briefly to initiate the turn, then push off on your back",
      easyDistractors:["You must stay on your back the entire turn","You can do any kind of flip and walk back"],
      hardDistractors:["You must touch with both hands first","You must stop fully before turning","You can switch to freestyle for the turn"],
      hint:"There's a small window where you can rotate."},
    {id:"sw-32", type:"tf", panel:5,
      prompt:"Freestyle requires breathing only on every third stroke.", answer:false,
      hint:"Freestyle has no rule about how often you breathe."},
    {id:"sw-33", type:"mc", panel:5,
      prompt:"What helps you swim freestyle in a straight line?",
      answer:"Following the line on the bottom of the pool",
      easyDistractors:["Closing your eyes the whole time","Singing to yourself"],
      hardDistractors:["Watching the swimmer next to you","Following the lane rope with your hand","Listening for the coach's voice"],
      hint:"Look down through your goggles."},

    /* ---------- Panel 6: Breaststroke & Butterfly ---------- */
    {id:"sw-34", type:"mc", panel:6,
      prompt:"What kick is used in breaststroke?",
      answer:"A frog (whip) kick — both legs together, symmetrical",
      easyDistractors:["A flutter kick like freestyle","No kicking at all"],
      hardDistractors:["A dolphin kick","A scissor kick","A bicycle kick"],
      hint:"Like a frog jumping."},
    {id:"sw-35", type:"mc", panel:6,
      prompt:"What kick is used in butterfly?",
      answer:"Dolphin kick (both legs together)",
      easyDistractors:["No kick at all","Bicycle kick"],
      hardDistractors:["Frog kick","Flutter kick","Scissor kick"],
      hint:"Both legs move as one — like a dolphin's tail."},
    {id:"sw-36", type:"tf", panel:6,
      prompt:"In breaststroke and butterfly, you must touch the wall with both hands at the same time at the finish and turns.",
      answer:true,
      hint:"Two-hand simultaneous touch."},
    {id:"sw-37", type:"mc", panel:6,
      prompt:"How do butterfly swimmers move their arms?",
      answer:"Both arms together over the water at the same time",
      easyDistractors:["One arm only, the other behind the back","Arms held still"],
      hardDistractors:["Alternating like freestyle","One arm at a time, very slowly","Arms underwater only"],
      hint:"Like wings."},
    {id:"sw-38", type:"tf", panel:6,
      prompt:"In breaststroke you may take more than one pull and one kick per cycle.", answer:false,
      hint:"One pull, one kick, breathe — repeat."},
    {id:"sw-39", type:"mc", panel:6,
      prompt:"After a breaststroke start, how many underwater strokes are allowed (in most rules)?",
      answer:"One arm pull and one kick (with a single butterfly kick allowed at start in many rules)",
      easyDistractors:["As many as you want","Zero — you must surface immediately"],
      hardDistractors:["Three pulls and three kicks","Two pulls and one kick","Only kicks, no pulls"],
      hint:"Just one full underwater stroke cycle."},

    /* ---------- Panel 7: Relay Rules ---------- */
    {id:"sw-40", type:"mc", panel:7,
      prompt:"How many swimmers are on a relay team?",
      answer:"4",
      easyDistractors:["1","20"],
      hardDistractors:["2","3","5"],
      hint:"Four legs of the relay."},
    {id:"sw-41", type:"tf", panel:7,
      prompt:"The next swimmer can leave the block before the previous swimmer touches the wall.",
      answer:false,
      hint:"Leaving early is an exchange violation."},
    {id:"sw-42", type:"mc", panel:7,
      prompt:"What is a relay 'exchange'?",
      answer:"The moment one swimmer finishes and the next swimmer starts",
      easyDistractors:["Switching swimsuits","Trading lanes"],
      hardDistractors:["Picking the order","Coaching the next swimmer","Swapping caps"],
      hint:"It's the changeover at the wall."},
    {id:"sw-43", type:"mc", panel:7,
      prompt:"In a medley relay, what is the order of strokes?",
      answer:"Backstroke, breaststroke, butterfly, freestyle",
      easyDistractors:["Freestyle only","Whatever the team picks"],
      hardDistractors:["Butterfly, backstroke, breaststroke, freestyle","Breaststroke, butterfly, backstroke, freestyle","Freestyle, butterfly, breaststroke, backstroke"],
      hint:"It starts with the stroke that begins in the water."},
    {id:"sw-44", type:"tf", panel:7,
      prompt:"All four relay swimmers must complete their leg for the team to be officially scored.",
      answer:true,
      hint:"No one can skip their leg."},
    {id:"sw-45", type:"mc", panel:7,
      prompt:"If a swimmer leaves the block too early on an exchange, what usually happens?",
      answer:"The relay is disqualified",
      easyDistractors:["Nothing — it's fine","Extra points are awarded"],
      hardDistractors:["Only that leg is re-swum","The next swimmer is replaced","Time is added as a penalty"],
      hint:"Same as a false start, basically."},

    /* ---------- Panel 8: Sportsmanship & Etiquette ---------- */
    {id:"sw-46", type:"mc", panel:8,
      prompt:"What should you do after your race, win or lose?",
      answer:"Congratulate the other swimmers in your heat",
      easyDistractors:["Splash them angrily","Complain to the officials"],
      hardDistractors:["Demand a re-swim","Run laps around the pool","Take their cap"],
      hint:"Good sportsmanship!"},
    {id:"sw-47", type:"tf", panel:8,
      prompt:"It's polite to shake hands or say 'good race' to the other swimmers after the race.", answer:true,
      hint:"Respect your competition."},
    {id:"sw-48", type:"mc", panel:8,
      prompt:"What's the right way to behave on the pool deck?",
      answer:"Walk, don't run; respect lifeguards and officials",
      easyDistractors:["Run as fast as possible","Push other swimmers in"],
      hardDistractors:["Sit on the lane lines","Cheer through other swimmers' starts","Drop equipment in lanes"],
      hint:"Wet deck = slippery."},
    {id:"sw-49", type:"tf", panel:8,
      prompt:"You should listen carefully to officials and follow their directions.", answer:true,
      hint:"They keep the meet safe and fair."},
    {id:"sw-50", type:"mc", panel:8,
      prompt:"When another swimmer is starting their race, you should…",
      answer:"…stay quiet so they can hear the start signal",
      easyDistractors:["…shout to distract them","…blow a whistle"],
      hardDistractors:["…run past their lane","…clap as loud as you can","…talk to your friends nearby"],
      hint:"Respect the start."}
  ]
};

if (typeof window !== "undefined") window.QUESTIONS = QUESTIONS;
